/*
 RequireJS domReady 2.0.1 Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/requirejs/domReady for details
 MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors */
define("third_party/domready/domReady",[],function(){function d(){if(!e){e=!0;f&&clearInterval(f);var a=m;if(e&&a.length){m=[];var b;for(b=0;b<a.length;b+=1)a[b](l)}}}function b(a){e?a(l):m.push(a);return b}var c,a,f,g="undefined"!==typeof window&&window.document,e=!g,l=g?document:null,m=[];if(g){if(document.addEventListener)document.addEventListener("DOMContentLoaded",d,!1),window.addEventListener("load",d,!1);else if(window.attachEvent){window.attachEvent("onload",d);a=document.createElement("div");
try{c=null===window.frameElement}catch(k){}a.doScroll&&c&&window.external&&(f=setInterval(function(){try{a.doScroll(),d()}catch(b){}},30))}"complete"===document.readyState&&d()}b.version="2.0.1";b.load=function(a,c,d,f){f.isBuild?d(null):b(d)};return b});
define("qowtRoot/utils/typeUtils",[],function(){function d(a,b,d){if(d.types.every(function(a){var b=c[a];if(!b)throw Error("Bad config to checkArgTypes: unknown type: "+a);return!b(d.value)})){var e=1===d.types.length?d.types[0]:"["+d.types.join(",")+"]";throw Error("Argument "+b+" passed to function "+a+" was supposed to be of type "+e+" but had value "+d.value);}}var b={checkArgTypes:function(a,b){for(var c in b){var e={value:b[c][0],types:b[c].slice(1)};d(a,c,e)}},isObject:function(a){return"object"===
typeof a&&null!==a},isPromise:function(a){return a instanceof Promise},isPromiseLike:function(a){return!(!a||!b.isFunction(a.then))},isList:function(a){return"[object Array]"===Object.prototype.toString.call(a)},isNumber:function(a){return"number"===typeof a&&!isNaN(a)},isInteger:function(a){return"number"===typeof a&&parseInt(a,10)===a},isFunction:function(a){return"function"===typeof a},isString:function(a){return"[object String]"===Object.prototype.toString.call(a)},isRegex:function(a){return"[object RegExp]"===
Object.prototype.toString.call(a)},isNode:function(a){return a instanceof Node},isNull:function(a){return null===a},isUndefined:function(a){return void 0===a},isBoolean:function(a){return"boolean"===typeof a},getType:function(a){var b;Object.keys(c).forEach(function(d){c[d](a)&&(b=d)});return b},isArgumentsObjectOrList:function(a){return a instanceof Object&&a.hasOwnProperty("length")},extend:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},createNewType:function(a){var b=function(){},
d={isOfType:function(a){return void 0!==a&&null!==a&&a.constructor===b},markAsType:function(a){Object.defineProperty(a,"constructor",{value:b,configurable:!1,writable:!1,enumerable:!1});return a}};if(a){if(c[a])throw Error("Already registered type "+a);c[a]=d.isOfType}return d}},c={string:b.isString,object:b.isObject,promise:b.isPromise,promiseLike:b.isPromiseLike,node:b.isNode,regex:b.isRegex,"function":b.isFunction,number:b.isNumber,list:b.isList,boolean:b.isBoolean,"null":b.isNull,undefined:b.isUndefined};
return b});(function(){var d={},b=window.sessionStorage.getItem("featureOverrides");b&&(d=JSON.parse(b));d.isRelease=!0;d.edit=!1;window.sessionStorage.setItem("featureOverrides",JSON.stringify(d));window.localStorage.removeItem("testsToInclude");window.localStorage.removeItem("builtInTests")})();define("configs/releaseFeatures",function(){});
(function(){var d={},b=window.sessionStorage.getItem("featureOverrides");b&&(d=JSON.parse(b));d.save=!!(window.chrome&&window.chrome.fileSystem&&window.chrome.fileSystem.chooseEntry);window.sessionStorage.setItem("featureOverrides",JSON.stringify(d))})();define("configs/chromeFeatures",function(){});define("qowtRoot/features/pack",[],function(){return{edit:!0,save:!1,pointEdit:!1,hats:!0}});
define("qowtRoot/features/utils",["qowtRoot/features/pack"],function(d){var b={isEnabled:function(a){a=d[a];return void 0===a?!1:a},enable:function(a){d[a]=!0},disable:function(a){d[a]=!1},setOverrides:function(a){for(var b in a)a.hasOwnProperty(b)&&(d[b]=a[b])},isDebug:function(){return void 0!==c?c:!b.isEnabled("isRelease")},setDebugOverride:function(a){c=a},clearDebugOverride:function(){c=void 0}},c;return b});
(function(d){d("qowtRoot/third_party/when/lib/timer",["require"],function(b){return{set:setTimeout,clear:clearTimeout}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/timed",[],function(){return function(b,c,a){a.prototype.delay=function(a){var c=this;return new this.constructor(function(d,l,m){c.then(function(c){b(function(){d(c)},a)},l,m)})};a.prototype.timeout=function(a,d){var e=this,l=1<arguments.length;return new this.constructor(function(m,k,p){var n=b(function(){k(l?d:Error("timed out after "+a+"ms"))},a);e.then(function(a){c(n);m(a)},function(a){c(n);k(a)},p)})};return a}})})("function"===typeof define&&define.amd?
define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/array",[],function(){return function(b){var c=Array.prototype.map,a=Array.prototype.reduce,d=Array.prototype.reduceRight,g=Array.prototype.forEach,e=b.resolve,l=b.all;b.any=function(a){return new b(function(b,c){function d(a){l.push(a);0===--f&&c(l)}var f=0,l=[];g.call(a,function(a){++f;e(a).then(b,d)});0===f&&b()})};b.some=function(a,c){return new b(function(b,d,f){function l(a){0<h&&(--h,v.push(a),0===h&&b(v))}function w(a){0<q&&(--q,A.push(a),0===q&&
d(A))}var h=0,q,v=[],A=[];g.call(a,function(a){++h;e(a).then(l,w,f)});c=Math.max(c,0);q=h-c+1;h=Math.min(c,h);0===h&&b(v)})};b.settle=function(a){return l(c.call(a,function(a){function b(){return a.inspect()}a=e(a);return a.then(b,b)}))};b.map=function(a,b,d){return l(c.call(a,function(a){return e(a).then(b,d)}))};b.reduce=function(b,c){function d(a,b,f){return e(a).then(function(a){return e(b).then(function(b){return c(a,b,f)})})}return 2<arguments.length?a.call(b,d,arguments[2]):a.call(b,d)};b.reduceRight=
function(a,b){function c(a,d,f){return e(a).then(function(a){return e(d).then(function(c){return b(a,c,f)})})}return 2<arguments.length?d.call(a,c,arguments[2]):d.call(a,c)};b.prototype.spread=function(a){return this.then(l).then(function(b){return a.apply(void 0,b)})};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/fatal",["require","./timer"],function(b){var c=b("./timer").set;return function(a){c(function(){throw a;},0)}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/flow",["require","./fatal"],function(b){function c(){throw new TypeError("catch predicate must be a function");}function a(a,b){return function(){a.call(this);return b}}function d(){}var g=b("./fatal");return function(b){function l(a,b){return function(c){return(b===Error||null!=b&&b.prototype instanceof Error?c instanceof b:b(c))?a.call(this,c):k(c)}}var m=b.resolve,k=b.reject,p=b.prototype["catch"];b.prototype.done=function(a,b){var c=this._handler;
c.when(this._maybeFatal,d,this,c.receiver,a,b)};b.prototype._maybeFatal=function(a){if(Object(a)===a)m(a)["catch"](this._fatal)};b.prototype._fatal=g;b.prototype["catch"]=b.prototype.otherwise=function(a){return 1===arguments.length?p.call(this,a):"function"!==typeof a?this.ensure(c):p.call(this,l(arguments[1],a))};b.prototype["finally"]=b.prototype.ensure=function(b){if("function"!==typeof b)return this;b=a(b,this);return this.then(b,b)};b.prototype["else"]=b.prototype.orElse=function(a){return this.then(void 0,
function(){return a})};b.prototype.yield=function(a){return this.then(function(){return a})};b.prototype.tap=function(a){return this.then(a).yield(this)};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});(function(d){d("qowtRoot/third_party/when/lib/inspect",[],function(){return function(b){b.prototype.inspect=function(){return this._handler.inspect()};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/iterate",[],function(){return function(b){function c(a,b,l,m){function k(k){return d(l(k)).then(function(){return c(a,b,l,a(k))})}return d(m).then(function(a){return d(b(a)).then(function(b){return b?a:k(a)})})}function a(b,c,l,m){function k(k,m){return d(l(k)).then(function(){return a(b,c,l,m)})}return d(m).then(function(a){return d(c(a)).then(function(c){return c?a:d(b(a)).spread(k)})})}var d=b.resolve;b.iterate=c;b.unfold=a;return b}})})("function"===
typeof define&&define.amd?define:function(d){module.exports=d()});(function(d){d("qowtRoot/third_party/when/lib/progress",[],function(){return function(b){b.prototype.progress=function(b){return this.then(void 0,void 0,b)};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/with",[],function(){return function(b){b.prototype["with"]=b.prototype.withThis=b.prototype._bindContext;return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/makePromise",[],function(){return function(b){function c(b){var c=this;this._handler=new n;a(b,function(a){c._handler.resolve(a)},function(a){c._handler.reject(a)},function(a){c._handler.notify(a)})}function a(a,b,c,d){try{a(b,c,d)}catch(f){c(f)}}function d(a){return new g(new z(new q(a)))}function g(a){this._handler=a}function e(a,b){if(a instanceof c){var d=a._handler.join();return b===d?new q(new TypeError("Promise cycle")):d}return E(a)?m(a):new h(a)}
function l(a){return a instanceof c?a._handler.join():m(a)}function m(a){try{var b=a.then;return"function"===typeof b?new w(b,a):new h(a)}catch(c){return new q(c)}}function k(){}function p(a){this.handler=a;if(this._isMonitored()){var b=this._env.promiseMonitor.captureStack();this.trace=a._addTrace(b)}}function n(a){this.consumers=[];this.receiver=a;this.handler=void 0;this.resolved=!1;this._isMonitored()&&(this.trace=this._env.promiseMonitor.captureStack())}function z(a){p.call(this,a)}function y(a,
b){p.call(this,a);this.receiver=b}function w(a,b){n.call(this);this.assimilated=!1;this.untrustedThen=a;this.thenable=b}function h(a){this.value=a}function q(a){this.value=a;this.observed=!1;this._isMonitored()&&(this.key=this._env.promiseMonitor.startTrace(a))}function v(){return{state:"pending"}}function A(a,b,c,d,f,g,l,e){this.a=a;this.b=b;this.c=c;this.d=d;this.e=f;this.f=g;this.g=l;this.handler=e}function D(a,b){this.q=a;this.value=b}function E(a){return("object"===typeof a||"function"===typeof a)&&
null!==a}function B(a,b,c){try{return a.call(c,b)}catch(g){return d(g)}}function t(){}var C,x=b.scheduler,u=Object.create||function(a){function b(){}b.prototype=a;return new b};c.resolve=function(a){return a instanceof c?a:new g(new z(e(a)))};c.reject=d;c.never=function(){return C};c._defer=function(){return new g(new n)};c.prototype.then=function(a,b,c){var d=this._handler,f=new n(d.receiver);d.when(f.resolve,f.notify,f,d.receiver,a,b,c);return new g(f)};c.prototype["catch"]=c.prototype.otherwise=
function(a){return this.then(void 0,a)};c.prototype._bindContext=function(a){return new g(new y(this._handler,a))};c.all=function(a){function b(a,c,d,G){d.when(t,t,void 0,a,function(a){c[G]=a;0===--f&&this.resolve(c)},a.reject,a.notify)}var c=new n,d=a.length>>>0,f=d,e=[],k,h;for(k=0;k<d;++k)k in a?(h=a[k],E(h)?b(c,e,l(h),k):(e[k]=h,--f)):--f;0===f&&c.resolve(e);return new g(c)};c.race=function(a){if(Object(a)===a&&0===a.length)return C;for(var b=new n,c=0;c<a.length;++c)e(a[c]).when(t,t,void 0,b,
b.resolve,b.reject);return new g(b)};g.prototype=u(c.prototype);k.prototype.inspect=v;k.prototype.when=t;k.prototype.resolve=t;k.prototype.reject=t;k.prototype.notify=t;k.prototype.join=function(){return this};k.prototype._env=b.monitor||c;k.prototype._addTrace=t;k.prototype._isMonitored=function(){return"undefined"!==typeof this._env.promiseMonitor};p.prototype=u(k.prototype);p.prototype.join=function(){return this.handler.join()};p.prototype.inspect=function(){return this.handler.inspect()};p.prototype._addTrace=
function(a){return this.handler._addTrace(a)};n.prototype=u(k.prototype);n.prototype.inspect=function(){return this.resolved?this.handler.join().inspect():v()};n.prototype.resolve=function(a){this._join(e(a,this))};n.prototype.reject=function(a){this._join(new q(a))};n.prototype.join=function(){return this.resolved?this.handler.join():this};n.prototype.run=function(){var a=this.consumers,b=this.handler=this.handler.join();this.consumers=void 0;for(var c=0;c<a.length;c+=7)b.when(a[c],a[c+1],a[c+2],
a[c+3],a[c+4],a[c+5],a[c+6])};n.prototype._join=function(a){this.resolved||(this.resolved=!0,this.handler=a,x.enqueue(this),this._isMonitored()&&(this.trace=a._addTrace(this.trace)))};n.prototype.when=function(a,b,c,d,f,g,e){this.resolved?x.enqueue(new A(a,b,c,d,f,g,e,this.handler.join())):this.consumers.push(a,b,c,d,f,g,e)};n.prototype.notify=function(a){this.resolved||x.enqueue(new D(this.consumers,a))};n.prototype._addTrace=function(a){return this.resolved?this.handler._addTrace(a):a};z.prototype=
u(p.prototype);z.prototype.when=function(a,b,c,d,f,g,e){x.enqueue(new A(a,b,c,d,f,g,e,this.join()))};y.prototype=u(p.prototype);y.prototype.when=function(a,b,c,d,f,g,e){void 0!==this.receiver&&(d=this.receiver);this.join().when(a,b,c,d,f,g,e)};w.prototype=u(n.prototype);w.prototype.when=function(a,b,c,d,f,g,e){this.assimilated||(this.assimilated=!0,this._assimilate());n.prototype.when.call(this,a,b,c,d,f,g,e)};w.prototype._assimilate=function(){var a=this;this._try(this.untrustedThen,this.thenable,
function(b){a.resolve(b)},function(b){a.reject(b)},function(b){a.notify(b)})};w.prototype._try=function(a,b,c,d,f){try{a.call(b,c,d,f)}catch(g){d(g)}};h.prototype=u(k.prototype);h.prototype.inspect=function(){return{state:"fulfilled",value:this.value}};h.prototype.when=function(a,b,c,d,f){b="function"===typeof f?B(f,this.value,d):this.value;a.call(c,b)};q.prototype=u(k.prototype);q.prototype.inspect=function(){return{state:"rejected",reason:this.value}};q.prototype.when=function(a,b,c,g,e,l){this._isMonitored()&&
!this.observed&&this._env.promiseMonitor.removeTrace(this.key);this.observed=!0;b="function"===typeof l?B(l,this.value,g):d(this.value);a.call(c,b)};q.prototype._addTrace=function(a){this.observed||this._env.promiseMonitor.updateTrace(this.key,a)};C=new g(new k);A.prototype.run=function(){this.handler.when(this.a,this.b,this.c,this.d,this.e,this.f,this.g)};D.prototype.run=function(){for(var a=this.q,b=1;b<a.length;b+=7)this._notify(a[b],a[b+1],a[b+2],a[b+5])};D.prototype._notify=function(a,b,c,d){var f;
if("function"===typeof d)try{f=d.call(c,this.value)}catch(g){f=g}else f=this.value;a.call(b,f)};return c}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/Queue",[],function(){function b(b){this.head=this.tail=this.length=0;this.buffer=Array(1<<b)}b.prototype.push=function(b){this.length===this.buffer.length&&this._ensureCapacity(2*this.length);this.buffer[this.tail]=b;this.tail=this.tail+1&this.buffer.length-1;++this.length;return this.length};b.prototype.shift=function(){var b=this.buffer[this.head];this.buffer[this.head]=void 0;this.head=this.head+1&this.buffer.length-1;--this.length;return b};b.prototype._ensureCapacity=
function(b){var a=this.head,d=this.buffer,g=Array(b),e=0,l;if(0===a)for(l=this.length;e<l;++e)g[e]=d[e];else{b=d.length;for(l=this.tail;a<b;++e,++a)g[e]=d[a];for(a=0;a<l;++e,++a)g[e]=d[a]}this.buffer=g;this.head=0;this.tail=this.length};return b})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/scheduler",["require","./Queue"],function(b){function c(b){this._enqueue=b;this._handlerQueue=new a(15);var c=this;this.drainQueue=function(){c._drainQueue()}}var a=b("./Queue");c.prototype.enqueue=function(a){1===this._handlerQueue.push(a)&&this._enqueue(this.drainQueue)};c.prototype._drainQueue=function(){for(var a=this._handlerQueue;0<a.length;)a.shift().run()};return c})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/async",["require"],function(b){var c;return"undefined"!==typeof process&&null!==process&&"function"===typeof process.nextTick?function(a){process.nextTick(a)}:(c="function"===typeof MutationObserver&&MutationObserver||"function"===typeof WebKitMutationObserver&&WebKitMutationObserver)?function(a,b){var c,d=a.createElement("div");(new b(function(){var a=c;c=void 0;a()})).observe(d,{attributes:!0});return function(a){c=a;d.setAttribute("class","x")}}(document,
c):function(a){var b=setTimeout;return function(a){b(a,0)}}(b)})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});(function(d){d("qowtRoot/third_party/when/lib/Promise",["require","./makePromise","./scheduler","./async"],function(b){var c=b("./makePromise"),a=b("./scheduler");b=b("./async");return c({scheduler:new a(b),monitor:"undefined"!==typeof console?console:void 0})})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/when","require ./lib/timer ./lib/timed ./lib/array ./lib/flow ./lib/inspect ./lib/iterate ./lib/progress ./lib/with ./lib/Promise".split(" "),function(b){function c(a,b,c,d){var f=q(a);return 2>arguments.length?f:f.then(b,c,d)}function a(a){return function(){return g(a,this,v.call(arguments))}}function d(a){return g(a,this,v.call(arguments,1))}function g(a,b,c){return h.all(c).then(function(c){return a.apply(b,c)})}function e(){function a(b){d._handler.resolve(b)}
function b(a){d._handler.reject(a)}function c(a){d._handler.notify(a)}var d=h._defer();this.promise=d;this.resolve=a;this.reject=b;this.notify=c;this.resolver={resolve:a,reject:b,notify:c}}var l=b("./lib/timer"),m=b("./lib/timed"),k=b("./lib/array"),p=b("./lib/flow"),n=b("./lib/inspect"),z=b("./lib/iterate"),y=b("./lib/progress"),w=b("./lib/with"),h=b("./lib/Promise"),h=[k,p,z,y,n,w].reduceRight(function(a,b){return b(a)},m(l.set,l.clear,h)),q=h.resolve,v=Array.prototype.slice;c.promise=function(a){return new h(a)};
c.resolve=h.resolve;c.reject=h.reject;c.lift=a;c["try"]=d;c.attempt=d;c.iterate=h.iterate;c.unfold=h.unfold;c.join=function(){return h.all(arguments)};c.all=function(a){return c(a,h.all)};c.settle=function(a){return c(a,h.settle)};c.any=a(h.any);c.some=a(h.some);c.map=function(a,b){return c(a,function(a){return h.map(a,b)})};c.reduce=function(a,b){var d=v.call(arguments,1);return c(a,function(a){d.unshift(a);return h.reduce.apply(h,d)})};c.reduceRight=function(a,b){var d=v.call(arguments,1);return c(a,
function(a){d.unshift(a);return h.reduceRight.apply(h,d)})};c.isPromiseLike=function(a){return a&&"function"===typeof a.then};c.Promise=h;c.defer=function(){return new e};return c})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
define("qowtRoot/utils/promiseUtils",["qowtRoot/utils/typeUtils","qowtRoot/third_party/when/when"],function(d,b){var c={cast:function(a){return a instanceof Promise?a:Promise.resolve(a)},delay:function(a,b){a=a||0;return new Promise(function(c){setTimeout(c.bind(void 0,b),a)})},delayThenReject:function(a,b){a=a||0;return new Promise(function(c,d){setTimeout(d.bind(c,b),a)})},throwAndEscapeChain:function(a){a instanceof Error||(console.error("throwAndEscapeChain wrapping value in new Error: ",a),a=
Error(a));b.reject(a).done();throw a;},pipeline:function(a){function b(){for(var e=Array.prototype.slice.call(arguments,0);0<a.length;){var m=a.shift();if(d.isPromiseLike(m))return c.cast(m).then(function(c){a.unshift(c);return b.apply(g,e)});d.checkArgTypes("PromiseUtils.pipeline",{task:[m,"function"]});m=m.apply(g,e);if(d.isPromiseLike(m))return c.cast(m).then(function(a){return b(a)});e=[m]}return e[0]}var g=this,e=Array.prototype.slice.call(arguments,0);if(e.some(d.isPromiseLike))return Promise.all(e).then(function(a){return c.pipeline.apply(g,
a)});d.checkArgTypes("PromiseUtils.pipeline",{tasks:[a,"list"]});a=a.slice(0);return b.apply(g,e.slice(1))},finally:function(a,b){function d(){return c.cast(b()).then(function(){return a})}return c.cast(a).then(d,d)},waitForNextMacroTurn:function(a){return new Promise(function(b){window.setTimeout(b.bind(null,a),0)})}};return c});
define("qowtRoot/utils/platform",[],function(){var d=Object.create(Object.prototype,{name:{get:function(){return b}},locale:{get:function(){return c}},isOther:{get:function(){return"OTHER"===b}},isUnix:{get:function(){return"UNIX"===b}},isWindows:{get:function(){return"WINDOWS"===b}},isOsx:{get:function(){return"OSX"===b}},isLinux:{get:function(){return"LINUX"===b}},isCros:{get:function(){return"CROS"===b}}}),b,c;(function(){b="OTHER";var a=navigator.appVersion.toLowerCase();-1!==a.indexOf("x11")&&
(b="UNIX");-1!==a.indexOf("win")&&(b="WINDOWS");-1!==a.indexOf("mac")&&(b="OSX");-1!==a.indexOf("linux")&&(b="LINUX");-1!==a.indexOf("cros")&&(b="CROS");c=navigator.language.toUpperCase()})();return d});
define("utils/analytics/googleAnalytics",["qowtRoot/features/utils","qowtRoot/utils/promiseUtils","qowtRoot/utils/platform"],function(d,b,c){function a(a,b){var c;void 0!==t?c=t?Promise.resolve():Promise.reject(Error("ga permission cached (not permitted)")):(chrome&&chrome.metricsPrivate&&chrome.metricsPrivate.getIsCrashReportingEnabled&&(!d.isDebug()||void 0!==window.__gaMock)?c=Promise.resolve():(console.warn("GA not supported on this platform"),c=Promise.reject(Error("GA not supported on this platform"))),
c=c.then(f).catch(l));return c.then(m).then(a.bind(null,b)).catch(function(){})}function f(){var a=Error("Crash reporting setting timed out");return Promise.race([g(),b.delayThenReject(1E3,a)]).then(e)}function g(){return new Promise(function(a){chrome.metricsPrivate.getIsCrashReportingEnabled(a)})}function e(a){return new Promise(function(b,c){(t=a)?b():(console.warn("Crash reporting not allowed"),c())})}function l(){t=!1;return Promise.reject()}function m(){void 0===x&&k("QO");return Promise.resolve()}
function k(a){if(x=a)u=a,p(u);return Promise.resolve()}function p(a){B!==a&&(u=B=a,y({name:"page_view"}));return Promise.resolve()}function n(a){var b={name:"exception",parameters:{}};b.parameters.description=a.msg;b.parameters.fatal=a.fatal;y(b);return Promise.resolve()}function z(a){y(a);return Promise.resolve()}function y(a){var b=A[x],c=D[x];a.name=a.name?a.name:a.action;q().then(function(d){try{fetch(v+"?measurement_id="+b+"&api_secret="+c,{method:"POST",body:JSON.stringify({client_id:d,timestamp_micros:1E3*
(new Date).getTime(),events:[h(a)]})})}catch(e){console.error("Google Analytics request failed with an exception",e)}})}function w(a){if("10.0"===a)return"10";if("6.2"===a)return"8";if("6.1"===a)return"7";if("6.0"===a)return"Vista";if("5.1"===a)return"XP";if("5.0"===a)return"2000";a}function h(a){var b=a.name.replaceAll("-","_");if(!r){r={engagement_time_msec:100};r.session_id=C;r.app_version=chrome.runtime.getManifest().version;r.user_language=c.locale;r.operating_system="LINUX"===c.name?"Linux":
"WINDOWS"===c.name?"Windows":"CROS"===c.name?"Chrome OS":"OSX"===c.name?"Macintosh":c.name;r.screen_resolution=window.screen.width+"x"+window.screen.height;r.viewport=window.innerWidth+"x"+window.innerHeight;var d=r,e,f=/\(([^)]+)\)/.exec(navigator.userAgent)[1];c.isCros&&-1!==f.indexOf("CrOS")?e=f.match(/CrOS.*\d+(?:\.\d+)+/)[0].replace("CrOS ",""):c.isLinux&&-1!==f.indexOf("Linux")?e=/[^ ]*$/.exec(f)[0]:c.isOsx&&-1!==f.indexOf("Mac OS X")?(e=f.match(/\d+[._]\d+(?:[._]\d+)?/)[0].replaceAll("_","."),
1<e.match(/\./g).length&&(e=e.match(/^(\d+\.\d+)/)[0])):c.isWindows&&-1!==f.indexOf("Windows")&&(e=f.match(/\d+(?:\.\d+)+/)[0],e=w(e));d.operating_system_version=e;r.app_name=E}r.page_title=u;if(!a.parameters||"exception"!==a.name&&"page_view"!==a.name)r.event_category=a.category,a.label&&(r.event_label=a.label),a.value&&(r.value=a.value);else for(d=Object.keys(a.parameters),e=0;e<d.length;e++)r[d[e]]=a.parameters[d[e]];return{name:b,params:r}}function q(){F||(F=new Promise(function(a,b){chrome.storage.sync.get("clientId",
function(c){if(chrome.runtime.lastError)b(chrome.runtime.lastError);else if("undefined"===typeof c.clientId){var d=self.crypto.randomUUID();c={};c.clientId=d;chrome.storage.sync.set(c,function(){a(d)})}else a(c.clientId)})}));return F}var v="https://www.google-analytics.com/mp/collect",A={word:"G-2EHQ55R09Q",sheet:"G-429ETHTJYR",point:"G-5VSRBT2L9W",QO:"G-11BCJ4LWCJ"},D={word:"esgLzn1kRb6eHxjysYicgQ",sheet:"v9vcbIqZSe6pTYEryGsfUQ",point:"5uHsbBE-Q3-tHRTfVqEEXg",QO:"k2-sQUVpTZWoDAUgoGUwog"},E="Quickoffice",
B,t,C,x,u,r,F;return{setFileExt:function(a){},setSessionGroup:function(a){C=a},setTracker:function(b){return a(k,b)},setGA4Tracker:function(a){x=a},sendState:function(b){return a(p,b)},sendException:function(b){return a(n,b)},sendEvent:function(b){return a(z,b)},reset:function(){u=x=t=B=void 0}}});
define("qowtRoot/utils/i18n",["qowtRoot/utils/typeUtils","utils/analytics/googleAnalytics"],function(d,b){var c={getMessage:function(a,b){var g="????";if(!chrome||!chrome.i18n)return a;d.isString(a)?(g=chrome.i18n.getMessage(a,b),g||(g=a,c.logError_("Missing translation",a))):c.logError_("Invalid string translation Id",a);return g},logError_:function(a,c){console.error(a+" "+c);b.sendException({msg:a,fatal:!1})}};return c});
require(["third_party/domready/domReady!"],function(){require(["qowtRoot/utils/i18n"],function(d){var b=d.getMessage("extension_popup_new_document_header");document.getElementById("newHeading").textContent=b;var b=d.getMessage("extension_popup_new_spreadsheet_document"),b=createOption(b,"sheet"),c=d.getMessage("extension_popup_new_presentation_document"),c=createOption(c,"point"),a=d.getMessage("extension_popup_new_word_document"),a=createOption(a,"word"),f=document.getElementById("options");f.appendChild(b);
f.appendChild(c);f.appendChild(a);document.getElementById("messageBody").innerHTML=d.getMessage("extension_popup_message_body")})});function createOption(d,b){var c=document.createElement("div");c.id=b;c.textContent=d;var a=document.createElement("a");a.textContent=d;a.href="#";c.addEventListener("click",onClick,!0);return c}
function onClick(d){var b;"word"===d.target.id?b="application/vnd.openxmlformats-officedocument.wordprocessingml.document":"point"===d.target.id?b="application/vnd.openxmlformats-officedocument.presentationml.presentation":"sheet"===d.target.id&&(b="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");chrome.windows.getCurrent(function(c){chrome.runtime.sendMessage({newCreate:d.target.id,mimeType:b,currentWindowId:c.id},function(){window.close()})})}define("mainPopup",function(){});
